version: "2"

engines:
  rubocop:
    enabled: true
    channel: rubocop-1-39-0
  eslint:
    enabled: true
    channel: "eslint-7"
    extensions:
    - .js
    - .jsx
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true

ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.jsx"
  - "**.css"
  - Gemfile.lock

exclude_paths:
- public/*
- db/*
- fixtures/*
- vendor/*
- spec/*
- docs/*
- setup/*
- node_modules/*
- tmp/*
- coverage/*

# Essential quality checks - these prevent major code quality issues
checks:
  # Prevents overly complex methods (most important)
  method-complexity:
    config:
      threshold: 8
  
  # Prevents methods from becoming too long (crucial for maintainability)
  method-lines:
    config:
      threshold: 50
  
  # Prevents files from becoming massive (important for team collaboration)
  file-lines:
    config:
      threshold: 400
  
  # Prevents too many parameters (reduces complexity)
  argument-count:
    config:
      threshold: 5